apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "detector.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
  - apiGroups: ["devices.kubeedge.io"]
    resources: ["devices"]
    verbs: ["list", "get"]
