# Default values for detector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: piranhahu/detector
  tag: "1.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
